package stdgo._internal.io;
import stdgo._internal.errors.Errors;
@:keep var __init_go2hx__ = {
        try {
            var __tmp__0 = stdgo._internal.io.Io_errshortwrite.errShortWrite, __tmp__1 = stdgo._internal.io.Io__errinvalidwrite._errInvalidWrite, __tmp__2 = stdgo._internal.io.Io_errshortbuffer.errShortBuffer, __tmp__3 = stdgo._internal.io.Io_eof.eOF, __tmp__4 = stdgo._internal.io.Io_errunexpectedeof.errUnexpectedEOF, __tmp__5 = stdgo._internal.io.Io_errnoprogress.errNoProgress, __tmp__6 = stdgo._internal.io.Io__errwhence._errWhence, __tmp__7 = stdgo._internal.io.Io__erroffset._errOffset, __tmp__8 = stdgo._internal.io.Io_discard.discard, __tmp__9 = stdgo._internal.io.Io__blackholepool._blackHolePool, __tmp__10 = stdgo._internal.io.Io_errclosedpipe.errClosedPipe, __tmp__11 = stdgo._internal.io.Io___0.__0, __tmp__12 = stdgo._internal.io.Io___1.__1, __tmp__13 = stdgo._internal.io.Io___2.__2;
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
